import { motion, AnimatePresence } from 'framer-motion'
import { useEffect, useState } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'

const slides = [
  {
    title: 'Introduction to Machine Learning',
    subtitle: 'Understanding AI Fundamentals',
    tag: 'Title Slide',
    bullets: ['What is Machine Learning?', 'Types: Supervised, Unsupervised, RL', 'Real-world applications'],
    color: '#6366f1',
    bg: 'from-indigo-900/40 to-violet-900/20',
  },
  {
    title: 'Neural Networks',
    subtitle: 'How Deep Learning Works',
    tag: 'Concept Slide',
    bullets: ['Inspired by the human brain', 'Layers: Input → Hidden → Output', 'Backpropagation algorithm'],
    color: '#22d3ee',
    bg: 'from-cyan-900/40 to-indigo-900/20',
  },
  {
    title: 'Model Performance',
    subtitle: 'Accuracy & Loss Metrics',
    tag: 'Data Slide',
    bullets: ['Training accuracy: 97.3%', 'Validation loss: 0.042', 'F1 Score: 0.96'],
    color: '#8b5cf6',
    bg: 'from-violet-900/40 to-purple-900/20',
  },
  {
    title: 'Future of AI',
    subtitle: 'What Comes Next',
    tag: 'Conclusion',
    bullets: ['AGI by 2030s (projected)', 'Ethical AI frameworks', 'Human-AI collaboration'],
    color: '#10b981',
    bg: 'from-emerald-900/40 to-teal-900/20',
  },
  {
    title: 'Industry Applications',
    subtitle: 'AI Across Every Sector',
    tag: 'Applications',
    bullets: ['Healthcare: Diagnosis AI', 'Finance: Fraud Detection', 'Education: Personalized Learning'],
    color: '#f59e0b',
    bg: 'from-amber-900/40 to-orange-900/20',
  },
]

export default function DemoCarousel() {
  const [current, setCurrent] = useState(0)

  useEffect(() => {
    const t = setInterval(() => setCurrent((c) => (c + 1) % slides.length), 4000)
    return () => clearInterval(t)
  }, [])

  const prev = () => setCurrent((c) => (c - 1 + slides.length) % slides.length)
  const next = () => setCurrent((c) => (c + 1) % slides.length)

  const slide = slides[current]

  return (
    <section id="demo" className="py-32 px-6">
      <div className="max-w-5xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.6 }}
          className="text-center mb-16"
        >
          <p className="text-indigo-400 font-semibold text-sm uppercase tracking-widest mb-3">Live Demo</p>
          <h2 className="text-4xl lg:text-5xl font-bold text-white mb-4">
            See What AI <span className="gradient-text">Creates</span>
          </h2>
          <p className="text-white/50 text-lg">Real presentations generated by pptAI</p>
        </motion.div>

        <div className="relative">
          {/* Main slide */}
          <AnimatePresence mode="wait">
            <motion.div
              key={current}
              initial={{ opacity: 0, x: 30 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: -30 }}
              transition={{ duration: 0.4 }}
              className={`glass rounded-3xl p-10 bg-gradient-to-br ${slide.bg} min-h-[320px] relative overflow-hidden`}
              style={{ border: `1px solid ${slide.color}30` }}
            >
              {/* Slide tag */}
              <div
                className="absolute top-6 right-6 text-xs font-semibold px-3 py-1.5 rounded-full"
                style={{ background: `${slide.color}20`, color: slide.color, border: `1px solid ${slide.color}40` }}
              >
                {slide.tag}
              </div>

              {/* Slide number */}
              <div className="text-sm text-white/30 mb-3 font-medium">Slide {current + 1} of {slides.length}</div>

              {/* Title */}
              <h3 className="text-3xl font-bold text-white mb-2">{slide.title}</h3>
              <p className="text-base text-white/50 mb-8">{slide.subtitle}</p>

              {/* Bullets */}
              <div className="space-y-3">
                {slide.bullets.map((b, i) => (
                  <motion.div
                    key={i}
                    initial={{ opacity: 0, x: -10 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ delay: i * 0.1 }}
                    className="flex items-start gap-3"
                  >
                    <div
                      className="w-5 h-5 rounded-full flex items-center justify-center shrink-0 mt-0.5"
                      style={{ background: `${slide.color}30` }}
                    >
                      <div className="w-1.5 h-1.5 rounded-full" style={{ background: slide.color }} />
                    </div>
                    <span className="text-white/80 text-sm font-medium">{b}</span>
                  </motion.div>
                ))}
              </div>

              {/* Bottom image bar */}
              <div
                className="absolute bottom-0 left-0 right-0 h-1.5 rounded-b-3xl"
                style={{ background: `linear-gradient(90deg, ${slide.color}, transparent)` }}
              />
            </motion.div>
          </AnimatePresence>

          {/* Controls */}
          <div className="flex items-center justify-center gap-6 mt-8">
            <button
              onClick={prev}
              className="w-10 h-10 glass rounded-full flex items-center justify-center text-white/60 hover:text-white transition-colors"
            >
              <ChevronLeft size={18} />
            </button>
            <div className="flex gap-2">
              {slides.map((_, i) => (
                <button
                  key={i}
                  onClick={() => setCurrent(i)}
                  className="h-1.5 rounded-full transition-all duration-300"
                  style={{
                    width: i === current ? 24 : 6,
                    background: i === current ? slide.color : 'rgba(255,255,255,0.2)',
                  }}
                />
              ))}
            </div>
            <button
              onClick={next}
              className="w-10 h-10 glass rounded-full flex items-center justify-center text-white/60 hover:text-white transition-colors"
            >
              <ChevronRight size={18} />
            </button>
          </div>
        </div>
      </div>
    </section>
  )
}
